# Generated by Django 4.2.6 on 2024-09-21 17:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Internship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('all_places', models.IntegerField(verbose_name='all_places')),
                ('available_places', models.IntegerField(verbose_name='available_places')),
                ('time_type_work', models.TextField(verbose_name='time_type_work')),
                ('date_start', models.DateField(verbose_name='date_start')),
                ('date_end', models.DateField(verbose_name='date_end')),
                ('salary', models.IntegerField(verbose_name='salary')),
                ('description', models.TextField(default='', verbose_name='description')),
                ('company', models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to='companies.company')),
                ('company_address', models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to='companies.companyaddress')),
            ],
        ),
        migrations.CreateModel(
            name='Specialization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialization_name', models.TextField(verbose_name='specialization_name')),
            ],
        ),
        migrations.CreateModel(
            name='StudentResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response_text', models.TextField(verbose_name='response_text')),
                ('data_response', models.DateTimeField(verbose_name='data_response')),
                ('internship', models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to='internships.internship')),
                ('studentResponseFiles', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='InternshipSpecialization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('internship', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='internships.internship')),
                ('specialization', models.ForeignKey(default='', on_delete=django.db.models.deletion.SET_DEFAULT, to='internships.specialization')),
            ],
        ),
        migrations.CreateModel(
            name='FavoriteInternship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('internship', models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to='internships.internship')),
            ],
        ),
    ]
