# Generated by Django 4.2.6 on 2024-09-22 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('internships', '0002_alter_internship_all_places_and_more'),
        ('internships', '0002_rename_studentresponsefiles_studentresponse_student_and_more'),
    ]

    operations = [
    ]
