# Generated by Django 4.2.6 on 2024-09-21 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='file',
            options={'verbose_name': 'Файл', 'verbose_name_plural': 'Файлы'},
        ),
        migrations.RemoveField(
            model_name='file',
            name='user',
        ),
        migrations.AlterField(
            model_name='file',
            name='document_name',
            field=models.TextField(default='filef9b43004-2d77-49e5-b6ce-b132dd91c379', verbose_name='document_name'),
        ),
        migrations.AlterField(
            model_name='file',
            name='document_text',
            field=models.FileField(upload_to='files/addc52ac-7a9f-4d21-b11a-9409ccc9940e', verbose_name='document_text'),
        ),
    ]
