# Generated by Django 4.2.6 on 2024-09-21 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('student', 'Student'), ('company', 'Company'), ('educational_institution', 'Educational_institution')], default='student', max_length=25),
        ),
    ]
