# Generated by Django 4.2.6 on 2024-09-21 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='document_name',
            field=models.TextField(default='filef895c399-fdc2-4a31-a0a7-4f0f7e07378f', verbose_name='document_name'),
        ),
        migrations.AlterField(
            model_name='file',
            name='document_text',
            field=models.FileField(upload_to='files/f1f4ccef-3ee2-47cd-8b0d-bee672120a7e', verbose_name='document_text'),
        ),
    ]
