# Generated by Django 4.2.6 on 2024-09-22 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_file_options_remove_file_user_and_more'),
        ('accounts', '0003_alter_file_document_name_alter_file_document_text'),
    ]

    operations = [
    ]
