# Generated by Django 4.2.6 on 2024-09-22 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_file_document_name_alter_file_document_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='document_name',
            field=models.TextField(default='file18f82213-c2c3-4c40-b3e7-881bf50d734f', verbose_name='document_name'),
        ),
        migrations.AlterField(
            model_name='file',
            name='document_text',
            field=models.FileField(upload_to='files/e974571b-3587-4d24-9cb9-478808aa8ec5', verbose_name='document_text'),
        ),
    ]
