# Generated by Django 4.2.6 on 2024-09-22 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_file_document_name_alter_file_document_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='document_name',
            field=models.TextField(default='filef779636c-c929-4219-ad0f-88967f6fbdce', verbose_name='document_name'),
        ),
        migrations.AlterField(
            model_name='file',
            name='document_text',
            field=models.FileField(upload_to='files/6ebb3cea-60c9-4961-baeb-198e2f577ce7', verbose_name='document_text'),
        ),
    ]
