# Generated by Django 4.2.6 on 2024-09-22 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_file_document_name_alter_file_document_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='document_name',
            field=models.TextField(default='fileae68994f-7087-4ebf-a2fb-d431629fcaac', verbose_name='document_name'),
        ),
        migrations.AlterField(
            model_name='file',
            name='document_text',
            field=models.FileField(upload_to='files/319b51af-ece7-46de-9cd1-5f8b031a1cfa', verbose_name='document_text'),
        ),
    ]
