# Generated by Django 4.2.6 on 2024-09-22 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_file_document_name_alter_file_document_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='document_name',
            field=models.TextField(default='file1fa1f6a9-ba88-4c7b-a18b-4da221c8fea2', verbose_name='document_name'),
        ),
        migrations.AlterField(
            model_name='file',
            name='document_text',
            field=models.FileField(upload_to='files/10d7618d-bdfc-4273-b6c3-257b0f3021d0', verbose_name='document_text'),
        ),
    ]
