# Generated by Django 4.2.6 on 2024-09-22 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_file_document_name_alter_file_document_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='document_name',
            field=models.TextField(default='filebb10f496-916f-414d-a776-c3af51d56ea3', verbose_name='document_name'),
        ),
        migrations.AlterField(
            model_name='file',
            name='document_text',
            field=models.FileField(upload_to='files/34144987-ec9a-4095-8592-faede8a43bf1', verbose_name='document_text'),
        ),
    ]
